config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  },
                     skip: %i[sessions registrations]
  as :user do
    # ログイン
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    # ログアウト
    delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    # サインアップ
    get 'signup' => 'users/registrations#signup'
    get "/signup/registration" => "users/registrations#registration"
    post "signup/number" => "users/registrations#number"
    post "signup/address" => "users/registrations#address"
    post "signup/credit" => "users/registrations#credit"
    post "/signup/completed" => "users/registrations#create"
    get "/signup/done" => "users/registrations#done"
  end
  #   devise_scope :user do
  #   delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
  resources :products do
    resources :buys, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
    member do
      get 'logout'
      get 'confirmation'
      get 'profile'
    end
    resources :lists, only: :index
    resources :buy_lists, only: :index
    resources :cards, only: %i[index new create]
  end
  get '/users/:id/profile', to: 'users#plofile'
  get '/users/:id/confirmation', to: 'users#confirmation'
  resources :category1s, only: [] do
    resources :category2s, only: :index do
      resources :category3s, only: :index
    end
  end
  resources :relationships, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :address, dependent: :destroy
  has_one :credit, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :post

  validates :nickname, presence: true

  validates :last_name, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "名 に数字や特殊文字は使用できません" }, presence: true, unless: :uid?
  validates :first_name, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: "姓 に数字や特殊文字は使用できません" }, presence: true, unless: :uid?
  validates :last_name_kana, format: { with: /\A[ァ-ンー－]+\Z/, message: "名カナ を入力してください" }, presence: true, unless: :uid?
  validates :first_name_kana, format: { with: /\A[ァ-ンー－]+\Z/, message: "姓カナ を入力してください" }, presence: true, unless: :uid?
  validates :date_of_birth, presence: true, unless: :uid?

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  # フォローのみを考える
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  # フォローしているユーザーを特定
  has_many :followings, through: :following_relationships
  # フォローされることを考える
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  # フォローされているユーザーを特定
  has_many :followers, through: :follower_relationships

  # 現在のユーザーがフォーローしているかどうか
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  # フォローをする
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  # フォローを外す
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      uid: auth.uid,
      provider: auth.provider,
      nickname: User.dummy_nickname(auth),
      email: User.dummy_email(auth),
      password: Devise.friendly_token[0, 20]
    )

    user
 end

  private

  def self.dummy_email(auth)
    if auth.provider == "facebook" # facebook時の処理
      "#{auth.uid}-#{auth.provider}@example.com"
    else
      auth.info.email.to_s
    end
  end

  def self.dummy_nickname(auth)
    auth.info.name.to_s
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google_oauth2
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  prepend_before_action :check_captcha, only: %i[address new_user_session]
  prepend_before_action :customize_sign_up_params, only: [:address]
  protect_from_forgery except: :create
  def registration; end

  def address
    session[:nickname] = params[:session][:nickname]
    session[:email] = params[:session][:email]
    session[:password] = params[:session][:password]
    session[:password_confirmation] = params[:session][:password_confirmation]
    session[:last_name] = params[:session][:last_name]
    session[:first_name] = params[:session][:first_name]
    session[:last_name_kana] = params[:session][:last_name_kana]
    session[:first_name_kana] = params[:session][:first_name_kana]
    session[:date_of_birth] = params[:session][:date_of_birth]
  end

  def credit
    session[:zip_code] = params[:session][:zip_code]
    session[:prefecture] = params[:session][:prefecture]
    session[:city] = params[:session][:city]
    session[:address_line1] = params[:session][:address_line1]
    session[:address_line2] = params[:session][:address_line2]
    session[:phone_number] = params[:session][:phone_number]
  end

  def create
    token = params[:"payjp-token"]

    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana],
      date_of_birth: session[:date_of_birth]
    )
    @user.address = @user.build_address(
      zip_code: session[:zip_code],
      prefecture: session[:prefecture],
      city: session[:city],
      address_line1: session[:address_line1],
      address_line2: session[:address_line2],
      phone_number: session[:phone_number]
    )
    @user.credit = @user.build_credit(
      token: token
    )

    @user.save
    @user.address.save
    @user.credit.save

    if session[:user_id] = @user.id
      sign_up(@user, current_user)
      redirect_to action: 'done'
    else
      redirect_to action: 'registration'
    end
  end

  def done; end

  private

  def customize_sign_up_params
    devise_parameter_sanitizer.permit :sign_up, keys: %i[nickname email password password_confirmation last_name first_name last_name_kana first_name_kana date_of_birth]
  end

  def check_captcha
    unless verify_recaptcha(model: resource)
      self.resource = resource_class.new sign_up_params
      resource.validate
      respond_with_navigational(resource) { render :registration }
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  protect_from_forgery except: :destroy
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, except: [:new]

  def new; end

  def show
    @user = User.find(params[:id])
  end

  def logout; end

  def confirmation; end

  def profile; end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def move_to_index
    redirect_to '/' unless user_signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.haml
= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f|
  %div= f.hidden_field :following_id
  = f.submit "Follow", class: "btn btn-large btn-primary follow-btn"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_stats.html.haml
- @user ||= current_user
.stats
  = link_to "#{following_user_path(@user)}", class: "stats__following" do
    %strong#following.stat
      = @user.followings.count
    following
  = link_to "#{followers_user_path(@user)}", class: "stats__followers" do
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/users/_unfollow.html.haml
= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f|
  = f.submit "Unfollow", class: "btn btn-large follow-btn"

app/views/users/confirmation.html.haml
- breadcrumb :confirmation, @confirmation
= render "shared/header"
= render "shared/nav"
%main.mypage
  .mypage-body
    = render "shared/mypage-side"
    .mypage-content
      .mypage-content--confirmation
        %h2.mypage-content--confirmation__title
          本人情報の登録
        .mypage-content--confirmation__form
          .signup-form__group
            %p お客様の本人情報をご確認ください。
            %p 登録されたお名前、生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p
              = link_to "本人確認書類のアップロードについて>", "", class: "text-right"
          .signup-form__group
            %label お名前
            %p
              = current_user.last_name + current_user.first_name
          .signup-form__group
            %label お名前カナ
            %p
              = current_user.last_name_kana + current_user.first_name_kana
          .signup-form__group
            %label 生年月日
            %p
              = current_user.date_of_birth
          = form_for(:resource, url: "", method: :get) do |f|
            .signup-form__group
              %label 郵便番号
              %span 任意
              = f.text_field :zip_code, autofocus: true, autocomplete: "zip_code", placeholder: "例) 123-4567", class: "signup-form__group-inner"
            .signup-form__group
              %label 都道府県
              %span 任意
              = f.collection_select :prefecture, Prefecture.all, :id, :name, {prompt: "---"},class: "select-default signup-form__group-inner"
            .signup-form__group
              %label 市区町村
              %span 任意
              = f.text_field :city, autofocus: true, autocomplete: "city", placeholder: "例) 横浜市緑区", class: "signup-form__group-inner"
            .signup-form__group
              %label 番地
              %span 任意
              = f.text_field :address_line1, autofocus: true, autocomplete: "address_line1", placeholder: "例) 青山1-1-1", class: "signup-form__group-inner"
            .signup-form__group
              %label 建物名
              %span 任意
              = f.text_field :address_line2, autofocus: true, autocomplete: "address_line2", placeholder: "例) 柳ビル103", class: "signup-form__group-inner"
            .signup-form
              .actions
                = f.submit "登録する", class: "btn-red btn-default"
            .signup-form__group
              %p
                = link_to "本人情報の登録について>", "https://www.mercari.com/jp/help_center/article/423/", target: "_blank", class: "text-right"
= render "shared/footer"
= render "shared/sell-btn"

app/views/users/logout.html.haml
= render "shared/header"
%main.mypage
  .mypage-body
    = render "shared/mypage-side"
    .mypage-content
      .mypage-content--logout
        .mypage-content--logout__button
          = link_to 'ログアウト', destroy_user_session_path, method: :delete
= render "shared/footer"
= render "shared/sell-btn"

app/views/users/new.html.haml
%body
  .single
    =render "shared/header2"
    %main.single-main
      %section.main-container
        %h2.main-container__head 新規会員登録
        .main-container__inner
          .main-container__inner-content
            =link_to '', class: "btn-default btn-mail" do
              = fa_icon 'envelope', class: 'btn-mail__icon'
              メールアドレスで登録
            %button#facebook-login.btn-default.btn-sns.btn-sns__facebook
              = link_to "Facebookで登録", user_facebook_omniauth_authorize_path, method:'post'
              = fa_icon 'facebook', class: 'btn-sns__icon-facebook'
            %button#google-login.btn-default.btn-sns.btn-sns__google
              = link_to "Googleで登録", user_google_oauth2_omniauth_authorize_path, method:'post'
              = fa_icon 'google', class: 'btn-sns__icon-google'
    = render "shared/footer2"

app/views/users/profile.html.haml
- breadcrumb :profile, @profile
= render "shared/header"
= render "shared/nav"
%main.mypage
  .mypage-body
    = render "shared/mypage-side"
    .mypage-content
      .mypage-content--confirmation
        = form_for(:resource, url: "", method: :get) do |f|
          %h2.mypage-content--confirmation__title
            プロフィール
          %section.mypage-content--user--icon
            =link_to "" do
              %figure
                =image_tag("member_photo_noimage_thumb.png")
                = f.text_field :nickname, autofocus: true, autocomplete: "nickname", style: "height: 40px;width: 200px;"
          .mypage-content--confirmation__form
            .signup-form__group
              = f.text_area :zip_code, autofocus: true, autocomplete: "zip_code", class: "signup-form__group-inner", style: "height: 300px;"
            .signup-form
              .actions
                = f.submit "変更する", class: "btn-red btn-default"
= render "shared/footer"
= render "shared/sell-btn"

app/views/users/show.html.haml
- breadcrumb :user, @user
= render "shared/header"
= render "shared/nav"
%main.mypage
  .mypage-body
    = render "shared/mypage-side"
    = render "shared/mypage-main"
= render "shared/footer"
= render "shared/sell-btn"

app/views/users/show_follow.html.haml
- @user.followings.each do |user|
  %table
    %tr
      %td
        = user.nickname
      %td= link_to '詳細', user_path(user), style: "margin-left: 20px;"

app/views/users/show_follower.html.haml
- @user.followers.each do |user|
  %table
    %tr
      %td
        = user.nickname
      %td= link_to '詳細', user_path(user), style: "margin-left: 20px;"