config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  },
                     skip: %i[sessions registrations]
  as :user do
    # ログイン
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    # ログアウト
    delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    # サインアップ
    get 'signup' => 'users/registrations#signup'
    get "/signup/registration" => "users/registrations#registration"
    post "signup/number" => "users/registrations#number"
    post "signup/address" => "users/registrations#address"
    post "signup/credit" => "users/registrations#credit"
    post "/signup/completed" => "users/registrations#create"
    get "/signup/done" => "users/registrations#done"
  end
  #   devise_scope :user do
  #   delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
  resources :products do
    resources :buys, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
    member do
      get 'logout'
      get 'confirmation'
      get 'profile'
    end
    resources :lists, only: :index
    resources :buy_lists, only: :index
    resources :cards, only: %i[index new create]
  end
  get '/users/:id/profile', to: 'users#plofile'
  get '/users/:id/confirmation', to: 'users#confirmation'
  resources :category1s, only: [] do
    resources :category2s, only: :index do
      resources :category3s, only: :index
    end
  end
  resources :relationships, only: %i[create destroy]
end

app/views/shared/_cardindex-main.html.haml
.cardindex-content
  %section.cardindex-chapter-container
    %h2.cardindex-chapter-head
      支払い方法
    .cardindex-content-inner
      %section
        .cardindex-single-content
          %h3.cardindex-chapter-sub-head
            クレジットカード一覧
        .ul.settings-payment-list
      %section.setting-add-card
        .cardindex-single-content
          %button#google-login.btn-default.btn-sns.btn-sns__google
            = link_to new_user_card_path, class: "icon-card" do
              = fa_icon 'credit-card lg' , class: "icon-card"
              %span クレジットカードを追加する
      .settings-not-regist
        = link_to '', class: "hoge" do
          %span
            支払い方法について
            = fa_icon 'chevron-right ' , class: "icon-right"

app/views/shared/_comment.html.haml
.item-message
  .item-message__content
    - if @comments
      - @comments.each do |comment|
        %ul
          %li.clearfix
            = link_to '', class: "message-user" do
              .message-user__icon
                = image_tag ""
              .message-user__name
                = link_to comment.user.nickname
            .message-body
              .message-body__text
                = comment.text
                .message-body__text_delete
                = link_to '削除', product_comment_path(@product,comment), method: :delete
  .container
    - if current_user
      = form_for [@product,@comment] do
        %textarea{:cols => "30", :name => "text", :rows => "2"}
        %input{:type => "submit", :value => "コメントする"}/

app/views/shared/_footer.html.haml
%footer
  %aside.app-banner
    .app-banner--pc
      .app-banner--pc__inner
        %h2 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード!
        .app-banner--pc__icon
          = image_tag "icon.png", :width => "68"
          %ul
            %li
              =link_to 'https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8' do
                = image_tag "app-store.svg"
            %li{:style => "margin-left: 16px;"}
              =link_to 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja' do
                = image_tag "google-play.svg"
      %figure
        = image_tag "aside1.png", :width => "100%"
  %footer.footer
    %nav
      %li.footer-cell
        %h2.footer-cell--head メルカリについて
        %ul
          %li 会社概要(運営会社)
          %li プライバシーポリシー
          %li メルカリ利用規約
          %li 有償ポイントに関する特約
          %li あんしんスマホサポート制度に関する利用特約
          %li コンプライアンスポリシー
          %li 個人データの安全に管理に係る基本方針
          %li 特定商取引に関する表記
          %li 資金決済法に基づく表示
          %li 法令順守と犯罪防止のために
          %li 採用情報
      %li.footer-cell
        %h2.footer-cell--head メルカリを見る
        %ul
          %li カテゴリー一覧
          %li ブランド一覧
          %li 出品地域一覧
          %li 公式ブログ
          %li 公式Twiter
          %li 公式Facebook
      %li.footer-cell
        %h2.footer-cell--head ヘルプ&amp;ガイド
        %ul
          %li メルカリガイド
          %li メルカリロゴ利用ガイドライン
          %li お知らせ
          %li らくらくメルカリ便とは
          %li ゆうゆうメルカリ便とは
          %li 大型らくらくメルカリ便とは
          %li 車体取引ガイド
          %li 返品・返金ポリシー
          %li メルカリあんしん・あんぜん宣言!
          %li 偽ブランド品撲滅への取り組み
          %li メルカリボックス
      %li.footer-cell
        %h2.footer-cell--head 国
        %ul.footer-cell--lang
          %li
            =link_to 'https://www.mercari.com/' do
              = image_tag "us.png"
              United States
          %li
            =link_to 'https://www.mercari.com/uk/' do
              = image_tag "uk.png"
              United Kingdom
          %li
            =link_to 'https://www.mercari.com/jp/' do
              = image_tag "jp.png"
              日本
    =link_to '', class:'footer-logo' do
      = image_tag "logo-white.svg", class: "footer-logo-bottom"
    %p.footer-copyright ©︎ 2019 Mercari

app/views/shared/_footer2.html.haml
%footer.single-footer
  %ul.single-footer__list
    %li
      =link_to "プライバシーポリシー", ''
    %li
      =link_to "メルカリ利用規約", ''
    %li
      =link_to "特定商取引に関する表記", ''
    =link_to '', class: "single-footer__icon" do
      = image_tag "logo-gray.svg", width: "80", height: "65"
    %p.single-footer__small ©︎ 2019 Mercari

app/views/shared/_header.html.haml
%header.pc-header.visible-pc
  .pc-header-inner
    .clearfix
      %h1.l-left
        =link_to '/' do
          = image_tag "logo.svg", :height => "36", :width => "134", alt:"mercari"
      = search_form_for @q, url: search_products_path , class: 'pc-header-inner__form l-right' do |f|
        =f.text_field :name_cont,class: "input-default",placeholder: "キーワードから探す"
        = button_tag type:'submit', class: 'icon',id: 'sbtn2' do
          = fa_icon 'search'
    .pc-header-nav.clearfix
      %nav.l-left
        %ul.pc-header-nav__box
          %li
            %h2
              =link_to 'カテゴリーから探す', '', class: 'pc-header-nav__root'
          %li
            %h2
              =link_to 'ブランドから探す', '', class: 'pc-header-nav__root'
      .l-right
        %ul.pc-header-nav__login
          - if user_signed_in?
            %li.header-nav__my
              = link_to 'マイページ', "/users/#{current_user.id}"
            %li.header-nav__my
              = link_to 'お知らせ', "/users/:id"
            %li.header-nav__my
              = link_to 'やることリスト', "/users/:id"
          - else
            %li
              = link_to 'ログイン', new_user_session_path, method: :get, class: 'sp-header-btn button btn-red'
            %li
              = link_to '新規会員登録', signup_path , class: 'sp-header-btn button header-signup'

app/views/shared/_header2.html.haml
%header.single-header
  %h1.single-header__title
    =link_to '', class: "single-header__title-link" do
      = image_tag "logo.svg", width: "185", height: "49", class: "single-header-title-link-img"

app/views/shared/_mypage-main.html.haml
.mypage-content
  %section.mypage-content--user--icon
    =link_to "/" do
      %figure
        =image_tag("member_photo_noimage_thumb.png")
      = current_user.nickname
      .mypage-number
        %h2  評価 20 出品数 31
    = render 'stats'
    = render 'follow_form'
  %section.mypage-content--todo
    %ul.mypage-tabs
      %li.active
        %h3  お知らせ
      %li
        %h3  やることリスト
    .tab-content
      %ul
        %li
          =link_to "/", class: 'mypage-item-link' do
            %figure
              =image_tag("member_photo_noimage_thumb.png")
            .mypage-item-body
              %p  hhhrohiさんが「パンツ」にいいね！しました
              %p  １時間前
            %i.fa.fa-angle-right
        %li
          =link_to "/", class: 'mypage-item-link' do
            %figure
              =image_tag("member_photo_noimage_thumb.png")
            .mypage-item-body
              %p  hhhrohiさんが「パンツ」にいいね！しました
              %p  １時間前
            %i.fa.fa-angle-right
        %li.mypage-go-list
          =link_to "/", class: 'mypage-list' do
            一覧を見る
  %section.mypage-content--sold
    %h2.mypage-content--sold--tab  購入した商品
    %section.mypage-content--todo
      %ul.mypage-tabs
        %li.active
          %h3  取引中
        %li
          %h3  過去の取引
      .tab-content
        %ul
          %li
            %a.mypage-item-link
              %figure
                =image_tag("member_photo_noimage_thumb.png")
              .mypage-item-body
                %p  「CD」を購入しました。取引中です
                %p  １時間前
              %i.fa.fa-angle-right
          %li.mypage-go-list
            =link_to "/", class: 'mypage-list' do
              一覧を見る

app/views/shared/_mypage-side.html.haml
.mypage-side
  %nav.mypage-side--nav
    %ul.mypage-side--nav__ul
      %li.mypage-side--nav__ul__li
        =link_to "/users/#{current_user.id}" do
          %span  マイページ
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  お知らせ
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  やることリスト
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  いいね！一覧
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to new_product_path do
          %span  出品する
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/#{current_user.id}/lists" do
          %span  出品した商品-出品中
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/#{current_user.id}/lists" do
          %span  出品した商品-取引中
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/#{current_user.id}/lists" do
          %span  出品した商品-売却済み
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/#{current_user.id}/buy_lists" do
          %span  購入した商品-取引中
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/#{current_user.id}/buy_lists" do
          %span  購入した商品-過去の取引
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  ニュース一覧
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  評価一覧
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  ガイド
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  お問い合わせ
          %i.fa.fa-angle-right
    %h3  メルペイ
    %ul.mypage-side--nav__ul
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  売上・振込申請
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  ポイント
          %i.fa.fa-angle-right
    %h3  設定
    %ul.mypage-side--nav__ul
      %li.mypage-side--nav__ul__li
        =link_to "/users/:id/profile" do
          %span  プロフィール
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  発送元・お届け先住所変更
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to user_cards_path(current_user) do
          %span  支払方法
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  メール/パスワード
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/:id/confirmation" do
          %span  本人情報
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/" do
          %span  電話番号の確認
          %i.fa.fa-angle-right
      %li.mypage-side--nav__ul__li
        =link_to "/users/:id/logout" do
          %span  ログアウト
          %i.fa.fa-angle-right

app/views/shared/_product_card.html.haml
%section.items-box
  =link_to product_path(product) do
    %figure.items-box__photo
      = image_tag product.product_images.first.product_image unless product.product_images.blank?
    .items-box__body
      %h3.items-box__name
        = product.name
      .items-box__num
        .items-box__price
          ¥
          = number_with_delimiter(product.price)
        %p.items-box__tax (税込)
    -if product.sales_condition == 1
      %span SOLD OUT

app/views/shared/_product_image.html.haml
%li
  = image_tag product_image.product_image unless product_image.blank?

app/views/shared/_product_list.html.haml
%li
  =link_to  product_path(product), class: 'mypage-item-link' do
    %figure
      =image_tag("#{product.product_images.first.product_image}")
    .mypage-item-body
      %p #{product.name}
      %p #{SalesCondition.data[product.sales_condition.to_i].fetch(:name)}
    %i.fa.fa-angle-right

app/views/shared/_sell-btn.html.haml
=link_to new_product_path, class:'footer-sell-btn' do
  %div 出品
  = fa_icon 'camera', class: 'fa-3x'

app/views/shared/_slide.html.haml
%main.white{:role => "main"}
  %section
    .slideshow
      %input#switch1{:checked => "checked", :name => "slideshow", :type => "radio"}/
      %input#switch2{:name => "slideshow", :type => "radio"}/
      %input#switch3{:name => "slideshow", :type => "radio"}/
      %input#switch4{:name => "slideshow", :type => "radio"}/
      %input#switch5{:name => "slideshow", :type => "radio"}/
      .slideContents
        / = image_tag "main-img1.svg"
        = image_tag "main-img2.png"
        = image_tag "main-img3.png"
        = image_tag "main-img4.png"
        / = image_tag "main-img5.svg"
      %p.arrow.prev
        %i.ico
        %label{:for => "switch1"}
        %label{:for => "switch2"}
        %label{:for => "switch3"}
        %label{:for => "switch4"}
        %label{:for => "switch5"}
      %p.arrow.next
        %i.ico
        %label{:for => "switch1"}
        %label{:for => "switch2"}
        %label{:for => "switch3"}
        %label{:for => "switch4"}
        %label{:for => "switch5"}

app/views/shared/_sulide.html.haml
%main.white{:role => "main"}
  %section
    .slideshow
      %input#switch1{:checked => "checked", :name => "slideshow", :type => "radio"}/
      %input#switch2{:name => "slideshow", :type => "radio"}/
      %input#switch3{:name => "slideshow", :type => "radio"}/
      %input#switch4{:name => "slideshow", :type => "radio"}/
      %input#switch5{:name => "slideshow", :type => "radio"}/
      .slideContents
        %section#slide1
          = image_tag "main-img1.svg"
        %section#slide2
          = image_tag "main-img2.png"
        %section#slide3
          = image_tag "main-img3.png"
        %section#slide4
          = image_tag "main-img4.png"
        %section#slide5
          = image_tag "main-img5.svg"
      %p.arrow.prev
        %i.ico
        %label{:for => "switch1"}
        %label{:for => "switch2"}
        %label{:for => "switch3"}
        %label{:for => "switch4"}
        %label{:for => "switch5"}
      %p.arrow.next
        %i.ico
        %label{:for => "switch1"}
        %label{:for => "switch2"}
        %label{:for => "switch3"}
        %label{:for => "switch4"}
        %label{:for => "switch5"}