config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  },
                     skip: %i[sessions registrations]
  as :user do
    # ログイン
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    # ログアウト
    delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    # サインアップ
    get 'signup' => 'users/registrations#signup'
    get "/signup/registration" => "users/registrations#registration"
    post "signup/number" => "users/registrations#number"
    post "signup/address" => "users/registrations#address"
    post "signup/credit" => "users/registrations#credit"
    post "/signup/completed" => "users/registrations#create"
    get "/signup/done" => "users/registrations#done"
  end
  #   devise_scope :user do
  #   delete :sign_out, to: 'devise/sessions#destroy', as: :destroy_user_session
  # end
  resources :products do
    resources :buys, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
    member do
      get 'logout'
      get 'confirmation'
      get 'profile'
    end
    resources :lists, only: :index
    resources :buy_lists, only: :index
    resources :cards, only: %i[index new create]
  end
  get '/users/:id/profile', to: 'users#plofile'
  get '/users/:id/confirmation', to: 'users#confirmation'
  resources :category1s, only: [] do
    resources :category2s, only: :index do
      resources :category3s, only: :index
    end
  end
  resources :relationships, only: %i[create destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  has_one :order, dependent: :destroy
  belongs_to :user, optional: true
  accepts_nested_attributes_for :product_images
  belongs_to :category1
  belongs_to :category2
  belongs_to :category3
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :name, presence: true, length: { maximum: 40 }
  validates :product_description, presence: true, length: { maximum: 1000 }
  validates :category1, presence: true
  validates :condition, presence: true
  validates :postage, presence: true
  validates :ship_from, presence: true
  validates :shipping_date, presence: true
  validates :price, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :move_to_signup, except: %i[index show search]
  before_action :set_product, only: %i[show edit update destroy]
  protect_from_forgery except: :create

  def index; end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def show
    @product_images = @product.product_images
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
    @like = Like.new
  end

  def create
    @product = Product.new(product_sale_params)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.user_id == current_user.id
      @product.update(product_sale_params)
      redirect_to product_path
    end
  end

  def destroy
    @product.destroy if @product.user_id == current_user.id
    flash[:notice] = "商品を削除しました"
    redirect_to root_path
  end

  def search
    @product = Product.new
    @product.product_images.build
  end

  private

  def product_sale_params
    params.require(:product).permit(:name, :product_description, :category1_id, :category2_id, :category3_id, :brand, :postage, :price, :condition, :shipping_method, :ship_from, :shipping_date, :image, product_images_attributes: [:product_image]).merge(sales_condition: 0, user_id: current_user.id)
  end

  def move_to_signup
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/views/products/buy.html.haml
%body
  .single
    %header.single-header
      %h1.single-header__title
        =link_to '', class: "single-header__title-link" do
          = image_tag "logo.svg", width: "185", height: "49", class: "single-header-title-link-img"
    %main.single-main
      %section.main-container
        %h2.main-container__head 購入を確定しますか？
        .main-container__buyer
          .main-container__buyer-inner
            .buy-product-image
              = image_tag "buy-product-image"
            %p.buy-product-name
              #{@product.name}
            %form.buy-product
              %p.buy-product-price
                ¥
                = number_with_delimiter(@product.price)
                %span.buy-produt-postage
                  送料込み
                %ul.buy-according
                  %li.according-parent
                    .accordion-toggle
                      ポイントはありません
                %ul.buy-price-table
                  %li.buy-price-row
                    .buy-price-sell
                      支払い金額
                    .buy-price-sell
                      %span.data-buy-pay
                        ¥
                        = number_with_delimiter(@product.price)
                %p.has-error-text
                  配送先と支払い方法の入力を完了してください。
                .main-container__inner-content
                  %button#google-login.btn-default.btn-sns.btn-sns__google
                    購入する

        .main-container__buyer
          .main-container__buyer-inner
            %h3.buy-user-info
              配送先
            %adress.buy-user-info-text
              〒060-0000
              %br
              北海道 札幌市中央区1
              %br
              test_user
              %br
            %p.buy-user-info-text
              =link_to '' , class: "buy-user-info-fix" do
                %span 変更する >

        .main-container__buyer
          .main-container__buyer-inner
            %h3.buy-user-info-pay-method
              支払方法
            %p.buy-user-info-text
              %br
              未定
              %br
            %figure
            %p.buy-user-info-text
              =link_to '' , class: "buy-user-info-fix" do
                %span 変更する >

  = render "shared/footer2"

app/views/products/edit.html.haml
%body
  .single
    %header.single-header
      %h1.single-header__title
        =link_to '', class: "single-header__title-link" do
          = image_tag "logo.svg", width: "185", height: "49", class: "single-header-title-link-img"
    %main.single-main
      = form_for @product do |f|
        %section.main-container
          %h2.main-container__head 商品の情報を入力
          .main-container__seller
            %h3
              出品画像
              %span.must-icon 必須
            %p 最大10枚までアップロードできます
            = f.file_field :image
            .main-container__seller--image__upload
              %pre ドラッグアンドドロップまたはクリックしてファイルをアップロード
          .main-container__seller
            %h3
              商品名
              %span.must-icon 必須
            = f.text_field :name, class: 'input-default',placeholder: "商品名（必須40文字まで）"
          .main-container__seller
            %h3
              商品の説明
              %span.must-icon 必須
            = f.text_area :product_description,class: 'textarea-default',placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'
          .main-container__seller
            %h3.main-container__seller--sell-sub-head 商品の詳細
            .main-container__seller--form
              .form-group
                %h3
                  カテゴリー
                  %span.must-icon 必須
                = f.collection_select :category1, Category.all, :id, :name, {prompt: "---"},class: "select-default"
              .form-group
                %h3
                  商品の状態
                  %span.must-icon 必須
                = f.collection_select :condition, Condition.all, :id, :name, {prompt: "---"},class: "select-default"
          .main-container__seller
            %h3.main-container__seller--sell-sub-head 配送について
            .main-container__seller--form
              .form-group
                %h3
                  配送料の負担
                  %span.must-icon 必須
                = f.collection_select :postage, Shippingpay.all, :id, :name, {prompt: "---"},class: "select-default"
            .main-container__seller--form
              .form-group
                %h3
                  発送元の地域
                  %span.must-icon 必須
                = f.collection_select :ship_from, Prefecture.all, :id, :name, {prompt: "---"},class: "select-default"
            .main-container__seller--form
              .form-group
                %h3
                  発送までの日数
                  %span.must-icon 必須
                = f.collection_select :shipping_date, Shippingday.all, :id, :name, {prompt: "---"},class: "select-default"
          .main-container__seller
            %h3.main-container__seller--sell-sub-head 販売価格(300〜9,999,999)
            .main-container__seller--form
              %ul.main-container__seller--form--sell-price
                %li.form-group
                  .clearfix
                    %label.l-left
                      価格
                      %span.form-require.must-icon 必須
                    .l-right.price-input
                      ￥
                      = f.text_field :price, class: 'input-default',placeholder: "例）300"
                %li.clearfix
                  .l-left 販売手数料 (10%)
                  .l-right -
                %li.clearfix
                  .l-left 販売利益
                  .l-right -
          .main-container__seller
            %p 禁止されている出品、行為を必ずご確認ください。
            %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            %p また、出品をもちまして加盟店規約に同意したことになります。
            .main-container__inner-content
              = f.submit '変更する',class: 'btn-default btn-sns btn-sns__google'
              %button#google-login.btn-default.btn-sns.btn-sns__google.back-button
                = link_to "もどる", product_path, class: 'back-button'
  = render "shared/footer2"

app/views/products/index.html.haml
%body
= render "shared/header"
= render "shared/slide"
= render "shared/main"
= render "shared/footer"
= render "shared/sell-btn"

app/views/products/new.html.haml
%body
  .single
    %header.single-header
      %h1.single-header__title
        =link_to root_path , class: "single-header__title-link" do
          = image_tag "logo.svg", width: "185", height: "49", class: "single-header-title-link-img"
    %main.single-main
      %section.main-container
        = form_for @product do |f|
          %h2.main-container__head 商品の情報を入力
          .main-container__seller
            %h3
              出品画像
              %span.must-icon 必須
            %p 最大5枚までアップロードできます
            - 5.times do |times|
              = f.fields_for :product_images do |i|
                = i.file_field :product_image
            .main-container__seller--image__upload
              %pre ドラッグアンドドロップまたはクリックしてファイルをアップロード
          .main-container__seller
            %h3
              商品名
              %span.must-icon 必須
            = f.text_field :name, class: 'input-default',placeholder: "商品名（必須40文字まで）"
          .main-container__seller
            %h3
              商品の説明
              %span.must-icon 必須
            = f.text_area :product_description,class: 'textarea-default',placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'
          .main-container__seller
            %h3.main-container__seller--sell-sub-head 商品の詳細
            .main-container__seller--form
              .form-group
                %h3
                  カテゴリー
                  %span.must-icon 必須
                - category1_options = Category1.order(:id).map { |c| [c.name, c.id, data: { children_path: category1_category2s_path(c) }] }
                = f.select :category1_id, category1_options, { prompt: "---" }, class: 'select-parent select-default'
                - category2s = @product.category1.try(:category2s) || []
                - category2_options = category2s.map { |c| [c.name, c.id, data: { path: category1_category2_category3s_path(c) }] }
                = f.select :category2_id, category2_options, { prompt: "---" }, class: 'select-children select-default', style: "display: none;"
                - category3s = @product.category2.try(:category3s) || []
                - category3_options = category3s.map { |c| [c.name, c.id] }
                = f.select :category3_id, category3_options, { prompt: "---" }, class: 'select-grandchildren select-default', style: "display: none;"
              .form-group
                %h3
                  商品の状態
                  %span.must-icon 必須
                = f.collection_select :condition, Condition.all, :id, :name, {prompt: "---"},class: "select-default"
          .main-container__seller
            %h3.main-container__seller--sell-sub-head 配送について
            .main-container__seller--form
              .form-group
                %h3
                  配送料の負担
                  %span.must-icon 必須
                = f.collection_select :postage, Shippingpay.all, :id, :name, {prompt: "---"},class: "select-default"
            .main-container__seller--form
              .form-group
                %h3
                  発送元の地域
                  %span.must-icon 必須
                = f.collection_select :ship_from, Prefecture.all, :id, :name, {prompt: "---"},class: "select-default"
            .main-container__seller--form
              .form-group
                %h3
                  発送までの日数
                  %span.must-icon 必須
                = f.collection_select :shipping_date, Shippingday.all, :id, :name, {prompt: "---"},class: "select-default"
          .main-container__seller
            %h3.main-container__seller--sell-sub-head 販売価格(300〜9,999,999)
            .main-container__seller--form
              %ul.main-container__seller--form--sell-price
                %li.form-group
                  .clearfix
                    %label.l-left
                      価格
                      %span.form-require.must-icon 必須
                    .l-right.price-input
                      ￥
                      = f.text_field :price, class: 'input-default input-price',placeholder: "例）300"
                %li.clearfix
                  .l-left 販売手数料 (10%)
                  .l-right
                    .input-fee ---
                %li.clearfix
                  .l-left 販売利益
                  .l-right
                    .input-profit ---
          .main-container__seller
            %p 禁止されている出品、行為を必ずご確認ください。
            %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            %p また、出品をもちまして加盟店規約に同意したことになります。
            .main-container__inner-content
              = f.submit '出品する',class: 'btn-default btn-sns btn-sns__google'
        =link_to root_path do
          %button.btn-default.back-button
            %span もどる
  = render "shared/footer2"

app/views/products/search.html.haml
- breadcrumb :search, @q
= render "shared/header"
= render "shared/nav"
%section.pickup-container.search.clearfix
  = search_form_for @q, url: search_products_path , class: "search-left" do |f|
    .search-left--order
      .search-left--order__form
        %h3 並び替え
        .search-left--order__form__btn.input-default
          = sort_link(@q, :price,"価格順")
        .search-left--order__form__btn.input-default
          = sort_link(@q, :created_at,"出品日時順")
    .search-left--tool
      %h3 詳細検索
      .search-left--tool__form
        =f.label :name_cont,"キーワードを追加する"
        =f.text_field :name_cont,class: "input-default"
      .search-left--tool__form
        =f.label :category1_id_eq,"カテゴリーを選択する"
        - category1_options = Category1.order(:id).map { |c| [c.name, c.id, data: { children_path: category1_category2s_path(c) }] }
        = f.select :category1_id_eq, category1_options, { prompt: "---" }, class: 'select-parent select-default'
        - category2s = @product.category1.try(:category2s) || []
        - category2_options = category2s.map { |c| [c.name, c.id, data: { path: category1_category2_category3s_path(c) }] }
        = f.select :category2_id_eq, category2_options, { prompt: "---" }, class: 'select-children select-default', style: "display: none;"
        - category3s = @product.category2.try(:category3s) || []
        - category3_options = category3s.map { |c| [c.name, c.id] }
        = f.select :category3_id_eq, category3_options, { prompt: "---" }, class: 'select-grandchildren select-default', style: "display: none;"
      .search-left--tool__form
        =f.label :price_gteq,"価格"
        =f.number_field :price_gteq,class: "input-default", placeholder: "¥ Min"
      .search-left--tool__form
        =f.label :price_lteq,"~"
        =f.number_field :price_lteq,class: "input-default", placeholder: "¥ Max"
      .search-left--tool__form
        =f.label :condition_in,"商品の状態",class: "search-left--tool__form__title"
        =f.collection_check_boxes :condition_in, Condition.all, :id, :name do |b|
          .search-left--tool__form__checkbox
            =b.check_box class: "checkbox-default"
            =b.label class: "label"
      .search-left--tool__form
        =f.label :postage_in,"配送料の負担",class: "search-left--tool__form__title"
        =f.collection_check_boxes :postage_in, Shippingpay.all, :id, :name do |b|
          .search-left--tool__form__checkbox
            =b.check_box class: "checkbox-default"
            =b.label class: "label"
      .search-left--tool__form
        =f.label :sales_condition_in,"販売状況",class: "search-left--tool__form__title"
        =f.collection_check_boxes :sales_condition_in, SalesCondition.all, :id, :name do |b|
          .search-left--tool__form__checkbox
            =b.check_box class: "checkbox-default"
            =b.label class: "label"
      .search-left--tool__btn
        = link_to "クリア", request.path, class: "btn-default btn-gray"
        = f.submit "完了", class: "btn-default btn-red"
  .items-box__container
    %h3 検索結果
    .items-box__content.clearfix
      = render partial: "shared/product_card", collection: @products, as: "product"
= render "shared/footer"
= render "shared/sell-btn"

app/views/products/show.html.haml
- breadcrumb :product, @product
= render "shared/header"
= render "shared/nav"
%section.item-box
  %h1.item-box__name
    = @product.name
  %p.item-box__sub
    = "『#{@product.name}』は、24回の取引実績を持つ#{@product.user.nickname}さんから出品されました。#{Prefecture.data[@product.ship_from.to_i].fetch(:name)}から#{Shippingday.data[@product.shipping_date.to_i].fetch(:name)}で発送されます。"
  .item-box__main.clearfix
    .item-box__main-photo
      %ul.thumb-item
        = render partial: "shared/product_image", collection: @product_images
      %ul.thumb-item-nav
        = render partial: "shared/product_image", collection: @product_images
      -if @product.sales_condition == 1
        %span SOLD OUT
    %table.item-box__main-detail
      %tbody
        %tr
          %th 出品者
          %td
            =link_to @product.user.nickname ,''
            .face
              %div
                = fa_icon 'apple', class: 'fas fa-grin'
                %span 24
              %div
                = fa_icon 'apple', class: 'fa-meh'
                %span 0
              %div
                = fa_icon 'apple', class: 'fa-dizzy'
                %span 0
        %tr
          %th カテゴリー
          %td
            =link_to Category1.find_by(id: @product.category1_id).name
            =link_to Category2.find_by(id: @product.category2_id).name
            =link_to Category3.find_by(id: @product.category3_id).name
        %tr
          %th ブランド
          %td
            =link_to @product.brand, ''
        %tr
          %th 商品の状態
          %td #{Condition.data[@product.condition.to_i].fetch(:name)}
        %tr
          %th 配送料の負担
          %td #{Shippingpay.data[@product.postage.to_i].fetch(:name)}
        %tr
          %th 配送の方法
          %td #{@product.shipping_method}
        %tr
          %th 配送元地域
          %td
            =link_to "#{Prefecture.data[@product.ship_from.to_i].fetch(:name)}" ''
        %tr
          %th 発送日の目安
          %td #{Shippingday.data[@product.shipping_date.to_i].fetch(:name)}
  .item-box__price
    %span.price
      = "￥" + number_with_delimiter(@product.price.to_s)
    %span.tax (税込)
    %span.shipping 送料込み

  - if @product.sales_condition == 1 && user_signed_in? && current_user.id == @product.user_id
    .item-box__buy-disable
      %span 売り切れました
    =link_to 'この商品を削除する', product_path , method: :delete,class: "item-box__buy", data: { confirm: "#{@product.name}を削除しますか？" }

  - elsif @product.sales_condition == 1
    .item-box__buy-disable
      %span 売り切れました

  - elsif user_signed_in? && current_user.id != @product.user_id
    =link_to "購入画面に進む", new_product_buy_path(@product) ,method: :get, class: "item-box__buy"

  - elsif user_signed_in? && current_user.id == @product.user_id
    =link_to 'この商品を編集する', edit_product_path , method: :get,class: "item-box__buy"
    =link_to 'この商品を削除する', product_path , method: :delete,class: "item-box__buy", data: { confirm: "#{@product.name}を削除しますか？" }

  - else
    =link_to "購入画面に進む",  new_user_session_path ,method: :get, class: "item-box__buy"

  .item-box__description
    %p
      = @product.product_description
  .item-box__button.clearfix
    .item-box__button-left
      =link_to '' do
        = fa_icon 'heart'
        #{@product.likes.count}
        %span
      - if user_signed_in? && current_user.already_liked?(@product)
        = button_to 'いいねを取り消す', product_like_path(@product), method: :delete
      - elsif user_signed_in?
        = button_to 'いいね', product_likes_path(@product)
      =link_to '' do
        = fa_icon 'flag'
        %span 不適切な商品の報告
    .item-box__button-right
      =link_to '' do
        = fa_icon 'lock'
        %span あんしん・あんぜんのへの取り組み
  = render "comments/comment"
.social-media
  %ul.social-media__box
    %li
      =link_to '' do
        = fa_icon 'facebook', class: "fa-facebook"
    %li
      =link_to '' do
        = fa_icon 'twitter', class: "fa-twitter"
    %li
      =link_to '' do
        = fa_icon 'pinterest', class: "fa-pinterest"
= render "shared/footer"